<?php

/**
 * @file
 * Contains mbta_transit.module.
 *
 * This file contains a hook to display the schedule content of
 * various MBTA routes using colors from the API.
 *
 */

/**
 * Implements hook_theme().
 */
function mbta_transit_theme($existing, $type, $theme, $path) {
  return [
    'route_display' => [
      'variables' => [
        'route_attributes' => [], 
        'types' => [],
      ],
    ],
    'schedule_display' => [
      'variables' => [
        'schedule_attributes' => [], 
        'route_id' => '',
        'today_date' => '',
      ],
    ],
  ];
}
